version: '3.8'

services:
  api-gateway:
    build:
      context: ../../
      dockerfile: apps/api-gateway/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:5000
    ports:
      - "5080:5000"
    depends_on:
      - registry
      - issuance
      - settlement
      - compliance
      - identity
    networks:
      - ois-network

  identity:
    build:
      context: ../../
      dockerfile: services/identity/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=ois;Username=ois;Password=ois_dev_password
    ports:
      - "5004:5000"
    depends_on:
      - postgres
    networks:
      - ois-network

  registry:
    build:
      context: ../../
      dockerfile: services/registry/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=ois;Username=ois;Password=ois_dev_password
    ports:
      - "5006:5000"
    depends_on:
      - postgres
    networks:
      - ois-network

  issuance:
    build:
      context: ../../
      dockerfile: services/issuance/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=ois;Username=ois;Password=ois_dev_password
      Kafka__BootstrapServers: kafka:9092
    ports:
      - "5005:5000"
    depends_on:
      - postgres
      - kafka
    networks:
      - ois-network

  settlement:
    build:
      context: ../../
      dockerfile: services/settlement/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=ois;Username=ois;Password=ois_dev_password
    ports:
      - "5007:5000"
    depends_on:
      - postgres
    networks:
      - ois-network

  compliance:
    build:
      context: ../../
      dockerfile: services/compliance/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=ois;Username=ois;Password=ois_dev_password
    ports:
      - "5008:5000"
    depends_on:
      - postgres
    networks:
      - ois-network

networks:
  ois-network:
    external: true
