apiVersion: v2
name: fabric-ca
description: A Helm chart for Hyperledger Fabric Certificate Authority
type: application
version: 0.1.0
appVersion: "1.5"
keywords:
  - hyperledger
  - fabric
  - blockchain
  - ca
maintainers:
  - name: OIS DevOps Team

