apiVersion: v2
name: chaincode-build
description: A Helm chart for Chaincode CI/CD pipeline
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - hyperledger
  - fabric
  - chaincode
  - cicd
maintainers:
  - name: OIS DevOps Team

