version: '3.8'

services:
  postgres:
    ports:
      - "${POSTGRES_HOST_PORT}:5432"

  zookeeper:
    ports:
      - "${ZOOKEEPER_HOST_PORT}:2181"

  kafka:
    ports:
      - "${KAFKA_HOST_PORT}:9092"

  keycloak:
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "${KEYCLOAK_HOST_PORT}:8080"

  minio:
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_HOST_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"

