{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fabric-orderer.fullname" . }}
  labels:
    {{- include "fabric-orderer.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "fabric-orderer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: orderer
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- with .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    - {} # Allow all egress
{{- end }}

