apiVersion: v1
kind: Service
metadata:
  name: {{ include "fabric-orderer.fullname" . }}
  labels:
    {{- include "fabric-orderer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: orderer
    - port: {{ .Values.config.general.cluster.listenPort }}
      targetPort: {{ .Values.config.general.cluster.listenPort }}
      protocol: TCP
      name: cluster
  selector:
    {{- include "fabric-orderer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: orderer

