apiVersion: v1
kind: Service
metadata:
  name: fabric-network-nlb
  namespace: fabric-network
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
    - name: orderer
      port: 7050
      targetPort: 7050
      protocol: TCP
    - name: peer0
      port: 7051
      targetPort: 7051
      protocol: TCP
    - name: peer1
      port: 8051
      targetPort: 8051
      protocol: TCP
    - name: ca
      port: 7054
      targetPort: 7054
      protocol: TCP
  selector:
    app.kubernetes.io/name: fabric-network

