apiVersion: v2
name: fabric-orderer
description: A Helm chart for Hyperledger Fabric Orderer nodes
type: application
version: 0.1.0
appVersion: "2.5"
keywords:
  - hyperledger
  - fabric
  - blockchain
  - orderer
maintainers:
  - name: OIS DevOps Team

