version: "3.9"
services:
  postgres:
    ports:
      - "${BIND_ADDR:-127.0.0.1}:${PORT_POSTGRES:-55432}:5432"
  kafka:
    ports:
      - "${BIND_ADDR:-127.0.0.1}:${PORT_KAFKA:-59092}:9092"
  zookeeper:
    ports:
      - "${BIND_ADDR:-127.0.0.1}:${PORT_ZOOKEEPER:-58181}:2181"
  keycloak:
    ports:
      - "${BIND_ADDR:-127.0.0.1}:${PORT_KEYCLOAK:-58090}:8080"
  minio:
    ports:
      - "${BIND_ADDR:-127.0.0.1}:${PORT_MINIO_API:-59000}:9000"
      - "${BIND_ADDR:-127.0.0.1}:${PORT_MINIO_CONSOLE:-59001}:9001"
